src/Entity/Identity.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IdentityRepository")
 */
class Identity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Skills", inversedBy="identities")
     */
    private $skills;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $site;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Formation", mappedBy="identity")
     */
    private $formations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Realisation", mappedBy="identity")
     */
    private $realisations;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pdf;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $git;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $linkedin;

    public function __construct()
    {
        $this->skills = new ArrayCollection();
        $this->formations = new ArrayCollection();
        $this->realisations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|skills[]
     */
    public function getSkills(): Collection
    {
        return $this->skills;
    }

    public function addSkill(skills $skill): self
    {
        if (!$this->skills->contains($skill)) {
            $this->skills[] = $skill;
        }

        return $this;
    }

    public function removeSkill(skills $skill): self
    {
        if ($this->skills->contains($skill)) {
            $this->skills->removeElement($skill);
        }

        return $this;
    }

    public function getSite(): ?string
    {
        return $this->site;
    }

    public function setSite(?string $site): self
    {
        $this->site = $site;

        return $this;
    }

    /**
     * @return Collection|Formation[]
     */
    public function getFormations(): Collection
    {
        return $this->formations;
    }

    public function addFormations(Formation $formation): self
    {
        if (!$this->formations->contains($formation)) {
            $this->formations[] = $formation;
            $formation->addIdentity($this);
        }

        return $this;
    }

    public function removeFormation(Formation $formation): self
    {
        if ($this->formations->contains($formation)) {
            $this->formations->removeElement($formation);
            $formation->removeIdentity($this);
        }

        return $this;
    }

    /**
     * @return Collection|Realisation[]
     */
    public function getRealisations(): Collection
    {
        return $this->realisations;
    }

    public function addRealisation(Realisation $realisation): self
    {
        if (!$this->realisations->contains($realisation)) {
            $this->realisations[] = $realisation;
            $realisation->setIdentity($this);
        }

        return $this;
    }

    public function removeRealisation(Realisation $realisation): self
    {
        if ($this->realisations->contains($realisation)) {
            $this->realisations->removeElement($realisation);
            // set the owning side to null (unless already changed)
            if ($realisation->getIdentity() === $this) {
                $realisation->setIdentity(null);
            }
        }

        return $this;
    }

    public function getPdf(): ?string
    {
        return $this->pdf;
    }

    public function setPdf(?string $pdf): self
    {
        $this->pdf = $pdf;

        return $this;
    }

    public function getGit(): ?string
    {
        return $this->git;
    }

    public function setGit(?string $git): self
    {
        $this->git = $git;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(?string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }

    
}

src/Controller/CvController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Identity;
use App\Entity\Skills;
use App\Entity\Formation;
use App\Repository\IdentityRepository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\Request;

class CvController extends AbstractController
{
    /**
     * @Route("/cv/{id}", name="cv")
     */
    public function index(?Identity $id, IdentityRepository $repo)
    {
        if($id == null){
            return $this->redirectToRoute('error_c_v');
        }
        // dd($id);
        return $this->render('cv/index.html.twig', [
            'controller_name' => 'CvController',
            'user' => $id,
            'skills' => $id->getSkills(),
            'formations' => $id->getFormations(),
            'realisations' => $id->getRealisations()
        ]);
    }
}

templates/cv/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CV de {{ user.firstName }} {{ user.lastName }} || PHP/Symfony {% endblock %}

{% block body %}
    <header>
        {% block jumb %}
            <div id="alert"></div>
            <div class="jumbotron" style="background-color:#1a2a50;color:#fff">
                <div class="pb-2 text-center">
                    <h1 class="display-4" style="color:#fff">{{ user.firstName }}  {{ user.lastName }}</h1>
                    <hr class="my-3">
                    <p><i class="fas fa-user" style="margin-right:10px;"></i>{{ user.email }} | {{ user.tel }}</p>
                    <p><a href="http://{{user.site}}" target="blank" style="color:#fff">Site internet</a></p>
                </div>
            </div>
        {% endblock %}
    </header>
    <main>
        <div class="container justify-content-center">   
            <div class="row">
                <div class="col-sm-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title"><i class="fab fa-dev"></i> Compétences</h4>
                            <ul>
                                {% for skill in skills %}
                                    <li>{{ skill.label }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 mb-3">
                    <div class="card diploma">
                        <div class="card-body">
                            <h4 class="card-title"><i class="fas fa-user-graduate"></i> Diplômes</h4>
                            <ul>
                                {% for formation in formations %}
                                    <li>{{ formation.title }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4 mb-3">
                    <div class="card real">
                        <div class="card-body">
                            <h4 class="card-title"><i class="fas fa-code"></i> Réalisations</h4>
                            <ul>
                                {% for realisation in realisations %}
                                    <li>{{ realisation.title }} {% if realisation.finished == 0 %}<span class="badge badge-pill badge-warning">Non terminé !</span>{% endif %}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </main>
    <footer>
        <div class="container mt-4 d-flex justify-content-center md-col-4">
            <a href="{{ asset('pdf/'~ user.pdf) }}" target="blank" class="btn btn-light ml-2 btn_blue pdf"><i class="fas fa-file-pdf"></i> Télécharger le CV de {{user.firstName}} {{user.lastName}} en PDF</a>
            <a href="{{ user.git }}" target="blank" class="btn btn-light ml-2 btn_blue git"><i class="fab fa-gitlab"></i> Gitlab de {{user.firstName}} {{user.lastName}}</a>
            <a href="{{ user.linkedin }}" class="btn btn-light ml-2 btn_blue linkedin" target="blank"><i class="fab fa-linkedin"></i> LinkedIn de {{user.firstName}} {{user.lastName}}</a>
            <p>
        </div>
    </footer>
{% endblock %}